language: node_js

node_js:
  - "8.11"

notifications:
  email: false

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build
  on:
    branch: master
